---

- name: Install Remi repo.
  yum:
    name: "https://rpms.remirepo.net/enterprise/remi-release-7.rpm"
    state: present

- name: Import Remi GPG key.
  rpm_key:
    key: "https://rpms.remirepo.net/RPM-GPG-KEY-remi"
    state: present

- name: Install EPEL repo.
  yum: name=epel-release state=present

- name: Install Node.js and npm.
  yum: name=npm state=present enablerepo=epel

    